[2025-02-28T15:04:08Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/pygeoapi/process/manager/base.py:509} INFO - Starting dummy manager
[2025-02-28T15:04:08Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/pygeoapi/api/__init__.py:568} INFO - Process manager plugin loaded
[2025-02-28T15:08:12Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/pygeoapi/process/manager/base.py:509} INFO - Starting dummy manager
[2025-02-28T15:08:12Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/pygeoapi/api/__init__.py:568} INFO - Process manager plugin loaded
[2025-02-28T15:08:12Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/werkzeug/_internal.py:97} INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:3456
 * Running on http://192.168.1.41:3456
[2025-02-28T15:08:12Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/werkzeug/_internal.py:97} INFO - [33mPress CTRL+C to quit[0m
[2025-02-28T15:08:12Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/werkzeug/_internal.py:97} INFO -  * Restarting with stat
[2025-02-28T15:08:13Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/pygeoapi/process/manager/base.py:509} INFO - Starting dummy manager
[2025-02-28T15:08:13Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/pygeoapi/api/__init__.py:568} INFO - Process manager plugin loaded
[2025-02-28T15:08:13Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/werkzeug/_internal.py:97} WARNING -  * Debugger is active!
[2025-02-28T15:08:13Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/werkzeug/_internal.py:97} INFO -  * Debugger PIN: 706-587-123
[2025-02-28T15:08:27Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/pygeoapi/l10n.py:87} WARNING - unknown locale 'bbox'
[2025-02-28T15:08:27Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/pygeoapi/l10n.py:87} WARNING - unknown locale 'crs'
[2025-02-28T15:08:27Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/pygeoapi/l10n.py:87} WARNING - unknown locale 'name'
[2025-02-28T15:08:27Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/pygeoapi/l10n.py:87} WARNING - unknown locale 'bundesland'
[2025-02-28T15:08:27Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/pygeoapi/l10n.py:87} WARNING - unknown locale 'emri_2020'
[2025-02-28T15:08:27Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/pygeoapi/l10n.py:87} WARNING - unknown locale 'emri_2021'
[2025-02-28T15:08:27Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/pygeoapi/l10n.py:87} WARNING - unknown locale 'rel'
[2025-02-28T15:08:27Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/pygeoapi/l10n.py:87} WARNING - unknown locale 'type'
[2025-02-28T15:08:27Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/pygeoapi/l10n.py:87} WARNING - unknown locale 'title'
[2025-02-28T15:08:27Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/pygeoapi/l10n.py:87} WARNING - unknown locale 'href'
[2025-02-28T15:08:27Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/pygeoapi/l10n.py:87} WARNING - unknown locale 'rel'
[2025-02-28T15:08:27Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/pygeoapi/l10n.py:87} WARNING - unknown locale 'type'
[2025-02-28T15:08:27Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/pygeoapi/l10n.py:87} WARNING - unknown locale 'title'
[2025-02-28T15:08:27Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/pygeoapi/l10n.py:87} WARNING - unknown locale 'href'
[2025-02-28T15:08:27Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/pygeoapi/l10n.py:87} WARNING - unknown locale 'rel'
[2025-02-28T15:08:27Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/pygeoapi/l10n.py:87} WARNING - unknown locale 'type'
[2025-02-28T15:08:27Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/pygeoapi/l10n.py:87} WARNING - unknown locale 'title'
[2025-02-28T15:08:27Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/pygeoapi/l10n.py:87} WARNING - unknown locale 'href'
[2025-02-28T15:08:27Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/werkzeug/_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 15:08:27] "GET /oapi/ HTTP/1.1" 200 -
[2025-02-28T15:08:27Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/werkzeug/_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 15:08:27] "[33mGET /static/css/default.css HTTP/1.1[0m" 404 -
[2025-02-28T15:08:27Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/werkzeug/_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 15:08:27] "[33mGET /static/img/pygeoapi.png HTTP/1.1[0m" 404 -
[2025-02-28T15:08:27Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/werkzeug/_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 15:08:27] "[33mGET /static/img/logo.png HTTP/1.1[0m" 404 -
[2025-02-28T15:08:27Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/werkzeug/_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 15:08:27] "GET /oapi/?f=jsonld HTTP/1.1" 200 -
[2025-02-28T15:08:27Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/werkzeug/_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 15:08:27] "[33mGET /static/img/favicon.ico HTTP/1.1[0m" 404 -
[2025-02-28T15:08:52Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/werkzeug/_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 15:08:52] "GET / HTTP/1.1" 200 -
[2025-02-28T15:08:52Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/werkzeug/_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 15:08:52] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
[2025-02-28T15:14:32Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/pygeoapi/api/__init__.py:617} ERROR - Invalid format requested: geojson
[2025-02-28T15:14:32Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/pygeoapi/api/__init__.py:585} ERROR - Invalid format requested
[2025-02-28T15:14:32Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/werkzeug/_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 15:14:32] "[31m[1mGET /oapi/collections/emri/items?f=geojson HTTP/1.1[0m" 400 -
[2025-02-28T15:18:23Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/werkzeug/_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 15:18:23] "GET /oapi/collections/emri HTTP/1.1" 200 -
[2025-02-28T15:18:23Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/werkzeug/_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 15:18:23] "[33mGET /static/css/default.css HTTP/1.1[0m" 404 -
[2025-02-28T15:18:23Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/werkzeug/_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 15:18:23] "[33mGET /static/img/pygeoapi.png HTTP/1.1[0m" 404 -
[2025-02-28T15:18:23Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/werkzeug/_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 15:18:23] "[33mGET /static/img/logo.png HTTP/1.1[0m" 404 -
[2025-02-28T15:18:23Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/werkzeug/_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 15:18:23] "[33mGET /static/img/logo.png HTTP/1.1[0m" 404 -
[2025-02-28T15:18:23Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/werkzeug/_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 15:18:23] "[33mGET /static/img/pygeoapi.png HTTP/1.1[0m" 404 -
[2025-02-28T15:18:23Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/werkzeug/_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 15:18:23] "GET /oapi/collections/emri?f=jsonld HTTP/1.1" 200 -
[2025-02-28T15:18:32Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/werkzeug/_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 15:18:32] "[33mGET /collections/emri/items HTTP/1.1[0m" 404 -
[2025-02-28T15:25:41Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/pygeoapi/api/itemtypes.py:244} WARNING - int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
[2025-02-28T15:25:41Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/pygeoapi/api/itemtypes.py:263} WARNING - int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
[2025-02-28T15:25:41Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/werkzeug/_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 15:25:41] "[35m[1mGET /oapi/collections/emri/items?f=json HTTP/1.1[0m" 500 -
[2025-02-28T15:25:41Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/werkzeug/_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 15:25:41] "GET /oapi/collections/emri/items?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
[2025-02-28T15:25:41Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/werkzeug/_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 15:25:41] "GET /oapi/collections/emri/items?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
[2025-02-28T15:25:41Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/werkzeug/_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 15:25:41] "GET /oapi/collections/emri/items?__debugger__=yes&cmd=resource&f=console.png&s=PsMUgP4KiqqV5XWuJKGA HTTP/1.1" 200 -
[2025-02-28T15:25:41Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/werkzeug/_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 15:25:41] "GET /oapi/collections/emri/items?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
[2025-02-28T15:28:32Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/werkzeug/_internal.py:97} INFO -  * Detected change in '/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/app.py', reloading
[2025-02-28T15:28:32Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/werkzeug/_internal.py:97} INFO -  * Restarting with stat
[2025-02-28T15:28:56Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/pygeoapi/process/manager/base.py:509} INFO - Starting dummy manager
[2025-02-28T15:28:56Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/pygeoapi/api/__init__.py:568} INFO - Process manager plugin loaded
[2025-02-28T15:28:56Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/werkzeug/_internal.py:97} INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:3456
 * Running on http://192.168.1.41:3456
[2025-02-28T15:28:56Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/werkzeug/_internal.py:97} INFO - [33mPress CTRL+C to quit[0m
[2025-02-28T15:28:56Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/werkzeug/_internal.py:97} INFO -  * Restarting with stat
[2025-02-28T15:28:57Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/pygeoapi/process/manager/base.py:509} INFO - Starting dummy manager
[2025-02-28T15:28:57Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/pygeoapi/api/__init__.py:568} INFO - Process manager plugin loaded
[2025-02-28T15:28:57Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/werkzeug/_internal.py:97} WARNING -  * Debugger is active!
[2025-02-28T15:28:57Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/werkzeug/_internal.py:97} INFO -  * Debugger PIN: 706-587-123
[2025-02-28T15:30:11Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/pygeoapi/process/manager/base.py:509} INFO - Starting dummy manager
[2025-02-28T15:30:11Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/pygeoapi/api/__init__.py:568} INFO - Process manager plugin loaded
[2025-02-28T15:30:11Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/werkzeug/_internal.py:97} INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:3456
 * Running on http://192.168.1.41:3456
[2025-02-28T15:30:11Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/werkzeug/_internal.py:97} INFO - [33mPress CTRL+C to quit[0m
[2025-02-28T15:30:11Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/werkzeug/_internal.py:97} INFO -  * Restarting with stat
[2025-02-28T15:30:11Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/pygeoapi/process/manager/base.py:509} INFO - Starting dummy manager
[2025-02-28T15:30:11Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/pygeoapi/api/__init__.py:568} INFO - Process manager plugin loaded
[2025-02-28T15:30:11Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/werkzeug/_internal.py:97} WARNING -  * Debugger is active!
[2025-02-28T15:30:11Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/werkzeug/_internal.py:97} INFO -  * Debugger PIN: 706-587-123
[2025-02-28T15:30:23Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/pygeoapi/api/itemtypes.py:244} WARNING - int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
[2025-02-28T15:30:23Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/pygeoapi/api/itemtypes.py:263} WARNING - int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
[2025-02-28T15:30:23Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/werkzeug/_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 15:30:23] "[35m[1mGET /oapi/collections/emri/items?f=json HTTP/1.1[0m" 500 -
[2025-02-28T15:30:23Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/werkzeug/_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 15:30:23] "[36mGET /oapi/collections/emri/items?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
[2025-02-28T15:30:23Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/werkzeug/_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 15:30:23] "[36mGET /oapi/collections/emri/items?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
[2025-02-28T15:30:23Z] {/Users/moritzdenk/Geoinformatics/Uni/SII/e-Mobility_Readiness_Index/venv/lib/python3.11/site-packages/werkzeug/_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 15:30:23] "GET /oapi/collections/emri/items?__debugger__=yes&cmd=resource&f=console.png&s=AoANVM4GILu8MBDaUP1o HTTP/1.1" 200 -
[2025-02-28T16:09:02Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\process\manager\base.py:509} INFO - Starting dummy manager
[2025-02-28T16:09:02Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\api\__init__.py:568} INFO - Process manager plugin loaded
[2025-02-28T16:09:03Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:3456
 * Running on http://192.168.178.39:3456
[2025-02-28T16:09:03Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - [33mPress CTRL+C to quit[0m
[2025-02-28T16:09:03Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO -  * Restarting with stat
[2025-02-28T16:09:05Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\process\manager\base.py:509} INFO - Starting dummy manager
[2025-02-28T16:09:05Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\api\__init__.py:568} INFO - Process manager plugin loaded
[2025-02-28T16:09:05Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} WARNING -  * Debugger is active!
[2025-02-28T16:09:05Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO -  * Debugger PIN: 234-497-827
[2025-02-28T16:09:37Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:09:37] "[33mGET /collections/emri/items?f=geojson HTTP/1.1[0m" 404 -
[2025-02-28T16:09:37Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:09:37] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
[2025-02-28T16:09:48Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:09:48] "GET / HTTP/1.1" 200 -
[2025-02-28T16:09:57Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:09:57] "[33mGET /collections HTTP/1.1[0m" 404 -
[2025-02-28T16:10:25Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:10:25] "[33mGET /collections HTTP/1.1[0m" 404 -
[2025-02-28T16:10:55Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'bbox'
[2025-02-28T16:10:55Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'crs'
[2025-02-28T16:10:55Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'name'
[2025-02-28T16:10:55Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'bundesland'
[2025-02-28T16:10:55Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'emri_2020'
[2025-02-28T16:10:55Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'emri_2021'
[2025-02-28T16:10:55Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'rel'
[2025-02-28T16:10:55Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'type'
[2025-02-28T16:10:55Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'title'
[2025-02-28T16:10:55Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'href'
[2025-02-28T16:10:55Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'rel'
[2025-02-28T16:10:55Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'type'
[2025-02-28T16:10:55Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'title'
[2025-02-28T16:10:55Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'href'
[2025-02-28T16:10:55Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'rel'
[2025-02-28T16:10:55Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'type'
[2025-02-28T16:10:55Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'title'
[2025-02-28T16:10:55Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'href'
[2025-02-28T16:10:55Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:10:55] "GET /oapi/collections/emri HTTP/1.1" 200 -
[2025-02-28T16:10:55Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:10:55] "[33mGET /static/css/default.css HTTP/1.1[0m" 404 -
[2025-02-28T16:10:55Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:10:55] "[33mGET /static/img/pygeoapi.png HTTP/1.1[0m" 404 -
[2025-02-28T16:10:55Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:10:55] "[33mGET /static/img/logo.png HTTP/1.1[0m" 404 -
[2025-02-28T16:10:55Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:10:55] "[33mGET /static/img/logo.png HTTP/1.1[0m" 404 -
[2025-02-28T16:10:55Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:10:55] "[33mGET /static/img/pygeoapi.png HTTP/1.1[0m" 404 -
[2025-02-28T16:10:55Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:10:55] "GET /oapi/collections/emri?f=jsonld HTTP/1.1" 200 -
[2025-02-28T16:10:56Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:10:56] "[33mGET /static/img/favicon.ico HTTP/1.1[0m" 404 -
[2025-02-28T16:11:39Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\api\itemtypes.py:244} WARNING - int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
[2025-02-28T16:11:39Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\api\itemtypes.py:263} WARNING - int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
[2025-02-28T16:11:40Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:11:40] "[35m[1mGET /oapi/collections/emri/items?f=json HTTP/1.1[0m" 500 -
[2025-02-28T16:11:40Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:11:40] "GET /oapi/collections/emri/items?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
[2025-02-28T16:11:40Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:11:40] "GET /oapi/collections/emri/items?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
[2025-02-28T16:11:40Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:11:40] "GET /oapi/collections/emri/items?__debugger__=yes&cmd=resource&f=console.png&s=6J2axiZwL7kJMjRweUI8 HTTP/1.1" 200 -
[2025-02-28T16:11:40Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:11:40] "GET /oapi/collections/emri/items?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
[2025-02-28T16:13:35Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\api\itemtypes.py:244} WARNING - int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
[2025-02-28T16:13:35Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\api\itemtypes.py:263} WARNING - int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
[2025-02-28T16:13:35Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:13:35] "[35m[1mGET /oapi/collections/emri/items HTTP/1.1[0m" 500 -
[2025-02-28T16:13:35Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:13:35] "[36mGET /oapi/collections/emri/items?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
[2025-02-28T16:13:35Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:13:35] "[36mGET /oapi/collections/emri/items?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
[2025-02-28T16:13:35Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:13:35] "[36mGET /oapi/collections/emri/items?__debugger__=yes&cmd=resource&f=console.png&s=6J2axiZwL7kJMjRweUI8 HTTP/1.1[0m" 304 -
[2025-02-28T16:17:03Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO -  * Detected change in 'C:\\Uni_Skripts\\SII_final\\e-Mobility_Readiness_Index\\app.py', reloading
[2025-02-28T16:17:03Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO -  * Restarting with stat
[2025-02-28T16:17:07Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\process\manager\base.py:509} INFO - Starting dummy manager
[2025-02-28T16:17:07Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\api\__init__.py:568} INFO - Process manager plugin loaded
[2025-02-28T16:17:08Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:3456
 * Running on http://192.168.178.39:3456
[2025-02-28T16:17:08Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - [33mPress CTRL+C to quit[0m
[2025-02-28T16:17:08Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO -  * Restarting with stat
[2025-02-28T16:17:10Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\process\manager\base.py:509} INFO - Starting dummy manager
[2025-02-28T16:17:10Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\api\__init__.py:568} INFO - Process manager plugin loaded
[2025-02-28T16:17:10Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} WARNING -  * Debugger is active!
[2025-02-28T16:17:10Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO -  * Debugger PIN: 234-497-827
[2025-02-28T16:17:12Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:17:12] "[33mGET /collections/emri.html HTTP/1.1[0m" 404 -
[2025-02-28T16:17:18Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:17:18] "[33mGET /collections/emri HTTP/1.1[0m" 404 -
[2025-02-28T16:17:28Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:17:28] "[33mGET /collections HTTP/1.1[0m" 404 -
[2025-02-28T16:17:30Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:17:30] "[33mGET /collections HTTP/1.1[0m" 404 -
[2025-02-28T16:17:36Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'bbox'
[2025-02-28T16:17:36Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'crs'
[2025-02-28T16:17:36Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'name'
[2025-02-28T16:17:36Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'bundesland'
[2025-02-28T16:17:36Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'emri_2020'
[2025-02-28T16:17:36Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'emri_2021'
[2025-02-28T16:17:36Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'rel'
[2025-02-28T16:17:36Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'type'
[2025-02-28T16:17:36Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'title'
[2025-02-28T16:17:36Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'href'
[2025-02-28T16:17:36Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'rel'
[2025-02-28T16:17:36Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'type'
[2025-02-28T16:17:36Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'title'
[2025-02-28T16:17:36Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'href'
[2025-02-28T16:17:36Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'rel'
[2025-02-28T16:17:36Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'type'
[2025-02-28T16:17:36Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'title'
[2025-02-28T16:17:36Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'href'
[2025-02-28T16:17:36Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:17:36] "GET /oapi/collections/emri HTTP/1.1" 200 -
[2025-02-28T16:17:36Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:17:36] "[33mGET /static/css/default.css HTTP/1.1[0m" 404 -
[2025-02-28T16:17:36Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:17:36] "[33mGET /static/img/logo.png HTTP/1.1[0m" 404 -
[2025-02-28T16:17:36Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:17:36] "[33mGET /static/img/pygeoapi.png HTTP/1.1[0m" 404 -
[2025-02-28T16:17:36Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:17:36] "[33mGET /static/img/logo.png HTTP/1.1[0m" 404 -
[2025-02-28T16:17:36Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:17:36] "[33mGET /static/img/pygeoapi.png HTTP/1.1[0m" 404 -
[2025-02-28T16:17:36Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:17:36] "GET /oapi/collections/emri?f=jsonld HTTP/1.1" 200 -
[2025-02-28T16:17:48Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\api\itemtypes.py:244} WARNING - int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
[2025-02-28T16:17:48Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\api\itemtypes.py:263} WARNING - int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
[2025-02-28T16:17:48Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:17:48] "[35m[1mGET /oapi/collections/emri/items?f=json HTTP/1.1[0m" 500 -
[2025-02-28T16:17:48Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:17:48] "[36mGET /oapi/collections/emri/items?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
[2025-02-28T16:17:48Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:17:48] "[36mGET /oapi/collections/emri/items?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
[2025-02-28T16:17:48Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:17:48] "GET /oapi/collections/emri/items?__debugger__=yes&cmd=resource&f=console.png&s=VUDVxjmP80pPj2WIJmbW HTTP/1.1" 200 -
[2025-02-28T16:30:57Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\process\manager\base.py:509} INFO - Starting dummy manager
[2025-02-28T16:30:57Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\api\__init__.py:568} INFO - Process manager plugin loaded
[2025-02-28T16:30:58Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:3456
 * Running on http://192.168.178.39:3456
[2025-02-28T16:30:58Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - [33mPress CTRL+C to quit[0m
[2025-02-28T16:30:58Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO -  * Restarting with stat
[2025-02-28T16:31:00Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\process\manager\base.py:509} INFO - Starting dummy manager
[2025-02-28T16:31:00Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\api\__init__.py:568} INFO - Process manager plugin loaded
[2025-02-28T16:31:00Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} WARNING -  * Debugger is active!
[2025-02-28T16:31:00Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO -  * Debugger PIN: 234-497-827
[2025-02-28T16:31:04Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:31:04] "[33mGET /collections/emri HTTP/1.1[0m" 404 -
[2025-02-28T16:31:07Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\api\itemtypes.py:244} WARNING - int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
[2025-02-28T16:31:07Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\api\itemtypes.py:263} WARNING - int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
[2025-02-28T16:31:08Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:31:08] "[35m[1mGET /oapi/collections/emri/items?f=json HTTP/1.1[0m" 500 -
[2025-02-28T16:31:08Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:31:08] "GET /oapi/collections/emri/items?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
[2025-02-28T16:31:08Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:31:08] "GET /oapi/collections/emri/items?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
[2025-02-28T16:31:08Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:31:08] "GET /oapi/collections/emri/items?__debugger__=yes&cmd=resource&f=console.png&s=ELOA3DoOcF5acVzbyy94 HTTP/1.1" 200 -
[2025-02-28T16:31:09Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\api\itemtypes.py:244} WARNING - int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
[2025-02-28T16:31:09Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\api\itemtypes.py:263} WARNING - int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
[2025-02-28T16:31:09Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:31:09] "[35m[1mGET /oapi/collections/emri/items?f=json HTTP/1.1[0m" 500 -
[2025-02-28T16:31:09Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:31:09] "[36mGET /oapi/collections/emri/items?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
[2025-02-28T16:31:09Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:31:09] "[36mGET /oapi/collections/emri/items?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
[2025-02-28T16:31:09Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:31:09] "[36mGET /oapi/collections/emri/items?__debugger__=yes&cmd=resource&f=console.png&s=ELOA3DoOcF5acVzbyy94 HTTP/1.1[0m" 304 -
[2025-02-28T16:32:23Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:32:23] "[33mGET /collections/emri HTTP/1.1[0m" 404 -
[2025-02-28T16:32:38Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:32:38] "[33mGET /collections/emri HTTP/1.1[0m" 404 -
[2025-02-28T16:32:48Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\api\itemtypes.py:244} WARNING - int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
[2025-02-28T16:32:48Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\api\itemtypes.py:263} WARNING - int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
[2025-02-28T16:32:48Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:32:48] "[35m[1mGET /oapi/collections/emri/items?f=json HTTP/1.1[0m" 500 -
[2025-02-28T16:32:48Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:32:48] "GET /oapi/collections/emri/items?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
[2025-02-28T16:32:48Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:32:48] "[36mGET /oapi/collections/emri/items?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
[2025-02-28T16:32:48Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:32:48] "GET /oapi/collections/emri/items?__debugger__=yes&cmd=resource&f=console.png&s=ELOA3DoOcF5acVzbyy94 HTTP/1.1" 200 -
[2025-02-28T16:32:51Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\api\itemtypes.py:244} WARNING - int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
[2025-02-28T16:32:51Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\api\itemtypes.py:263} WARNING - int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
[2025-02-28T16:32:51Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:32:51] "[35m[1mGET /oapi/collections/emri/items HTTP/1.1[0m" 500 -
[2025-02-28T16:32:51Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:32:51] "GET /oapi/collections/emri/items?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
[2025-02-28T16:32:51Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:32:51] "[36mGET /oapi/collections/emri/items?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
[2025-02-28T16:32:51Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:32:51] "GET /oapi/collections/emri/items?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
[2025-02-28T16:32:51Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:32:51] "GET /oapi/collections/emri/items?__debugger__=yes&cmd=resource&f=console.png&s=ELOA3DoOcF5acVzbyy94 HTTP/1.1" 200 -
[2025-02-28T16:32:55Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'bbox'
[2025-02-28T16:32:55Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'crs'
[2025-02-28T16:32:55Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'name'
[2025-02-28T16:32:55Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'bundesland'
[2025-02-28T16:32:55Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'emri_2020'
[2025-02-28T16:32:55Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'emri_2021'
[2025-02-28T16:32:55Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'rel'
[2025-02-28T16:32:55Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'type'
[2025-02-28T16:32:55Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'title'
[2025-02-28T16:32:55Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'href'
[2025-02-28T16:32:55Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'rel'
[2025-02-28T16:32:55Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'type'
[2025-02-28T16:32:55Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'title'
[2025-02-28T16:32:55Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'href'
[2025-02-28T16:32:55Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'rel'
[2025-02-28T16:32:55Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'type'
[2025-02-28T16:32:55Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'title'
[2025-02-28T16:32:55Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'href'
[2025-02-28T16:32:55Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:32:55] "GET /oapi/collections/emri HTTP/1.1" 200 -
[2025-02-28T16:32:55Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:32:55] "[33mGET /static/css/default.css HTTP/1.1[0m" 404 -
[2025-02-28T16:32:55Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:32:55] "[33mGET /static/img/pygeoapi.png HTTP/1.1[0m" 404 -
[2025-02-28T16:32:55Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:32:55] "[33mGET /static/img/logo.png HTTP/1.1[0m" 404 -
[2025-02-28T16:32:56Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:32:56] "[33mGET /static/img/logo.png HTTP/1.1[0m" 404 -
[2025-02-28T16:32:56Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:32:56] "[33mGET /static/img/pygeoapi.png HTTP/1.1[0m" 404 -
[2025-02-28T16:32:56Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:32:56] "GET /oapi/collections/emri?f=jsonld HTTP/1.1" 200 -
[2025-02-28T16:32:58Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:32:58] "GET /oapi/collections/emri HTTP/1.1" 200 -
[2025-02-28T16:32:58Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:32:58] "[33mGET /static/css/default.css HTTP/1.1[0m" 404 -
[2025-02-28T16:32:58Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:32:58] "[33mGET /static/img/pygeoapi.png HTTP/1.1[0m" 404 -
[2025-02-28T16:32:58Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:32:58] "[33mGET /static/img/logo.png HTTP/1.1[0m" 404 -
[2025-02-28T16:32:58Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:32:58] "[33mGET /static/img/logo.png HTTP/1.1[0m" 404 -
[2025-02-28T16:32:58Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:32:58] "[33mGET /static/img/pygeoapi.png HTTP/1.1[0m" 404 -
[2025-02-28T16:32:58Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:32:58] "GET /oapi/collections/emri?f=jsonld HTTP/1.1" 200 -
[2025-02-28T16:32:58Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:32:58] "GET /oapi/collections/emri HTTP/1.1" 200 -
[2025-02-28T16:32:58Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:32:58] "[33mGET /static/css/default.css HTTP/1.1[0m" 404 -
[2025-02-28T16:32:58Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:32:58] "[33mGET /static/img/logo.png HTTP/1.1[0m" 404 -
[2025-02-28T16:32:58Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:32:58] "[33mGET /static/img/pygeoapi.png HTTP/1.1[0m" 404 -
[2025-02-28T16:32:59Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:32:59] "GET /oapi/collections/emri?f=jsonld HTTP/1.1" 200 -
[2025-02-28T16:33:20Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\api\__init__.py:585} ERROR - Collection not found
[2025-02-28T16:33:20Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'bbox'
[2025-02-28T16:33:20Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'crs'
[2025-02-28T16:33:20Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'name'
[2025-02-28T16:33:20Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'bundesland'
[2025-02-28T16:33:20Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'emri_2020'
[2025-02-28T16:33:20Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'emri_2021'
[2025-02-28T16:33:20Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'rel'
[2025-02-28T16:33:20Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'type'
[2025-02-28T16:33:20Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'title'
[2025-02-28T16:33:20Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'href'
[2025-02-28T16:33:20Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'rel'
[2025-02-28T16:33:20Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'type'
[2025-02-28T16:33:20Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'title'
[2025-02-28T16:33:20Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'href'
[2025-02-28T16:33:20Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'rel'
[2025-02-28T16:33:20Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'type'
[2025-02-28T16:33:20Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'title'
[2025-02-28T16:33:20Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'href'
[2025-02-28T16:33:20Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:33:20] "[33mGET /oapi/collections/emri/items/ HTTP/1.1[0m" 404 -
[2025-02-28T16:33:20Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:33:20] "[33mGET /static/css/default.css HTTP/1.1[0m" 404 -
[2025-02-28T16:33:20Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:33:20] "[33mGET /static/img/logo.png HTTP/1.1[0m" 404 -
[2025-02-28T16:33:20Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:33:20] "[33mGET /static/img/pygeoapi.png HTTP/1.1[0m" 404 -
[2025-02-28T16:33:20Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\api\__init__.py:585} ERROR - Collection not found
[2025-02-28T16:33:20Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:33:20] "[33mGET /oapi/collections/emri/items/?f=jsonld HTTP/1.1[0m" 404 -
[2025-02-28T16:33:41Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\api\itemtypes.py:244} WARNING - int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
[2025-02-28T16:33:41Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\api\itemtypes.py:263} WARNING - int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
[2025-02-28T16:33:41Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:33:41] "[35m[1mGET /oapi/collections/emri/items?f=json HTTP/1.1[0m" 500 -
[2025-02-28T16:33:41Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:33:41] "GET /oapi/collections/emri/items?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
[2025-02-28T16:33:41Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:33:41] "GET /oapi/collections/emri/items?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
[2025-02-28T16:33:41Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:33:41] "GET /oapi/collections/emri/items?__debugger__=yes&cmd=resource&f=console.png&s=ELOA3DoOcF5acVzbyy94 HTTP/1.1" 200 -
[2025-02-28T16:33:41Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:33:41] "GET /oapi/collections/emri/items?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
[2025-02-28T16:35:50Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:35:50] "[33mGET /collections/emri.html HTTP/1.1[0m" 404 -
[2025-02-28T16:35:51Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:35:51] "[33mGET /collections/emri.html HTTP/1.1[0m" 404 -
[2025-02-28T16:35:52Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:35:52] "[33mGET /collections/emri.html HTTP/1.1[0m" 404 -
[2025-02-28T16:36:52Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\api\__init__.py:617} ERROR - Invalid format requested: geojson
[2025-02-28T16:36:52Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\api\__init__.py:585} ERROR - Invalid format requested
[2025-02-28T16:36:52Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:36:52] "[31m[1mGET /oapi/collections/emri/items?f=geojson HTTP/1.1[0m" 400 -
[2025-02-28T16:40:18Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\process\manager\base.py:509} INFO - Starting dummy manager
[2025-02-28T16:40:18Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\api\__init__.py:568} INFO - Process manager plugin loaded
[2025-02-28T16:40:19Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:3456
 * Running on http://192.168.178.39:3456
[2025-02-28T16:40:19Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - [33mPress CTRL+C to quit[0m
[2025-02-28T16:40:19Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO -  * Restarting with stat
[2025-02-28T16:40:20Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\process\manager\base.py:509} INFO - Starting dummy manager
[2025-02-28T16:40:20Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\api\__init__.py:568} INFO - Process manager plugin loaded
[2025-02-28T16:40:20Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} WARNING -  * Debugger is active!
[2025-02-28T16:40:20Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO -  * Debugger PIN: 234-497-827
[2025-02-28T16:40:42Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\api\itemtypes.py:244} WARNING - int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
[2025-02-28T16:40:42Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\api\itemtypes.py:263} WARNING - int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
[2025-02-28T16:40:43Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:40:43] "[35m[1mGET /oapi/collections/emri/items HTTP/1.1[0m" 500 -
[2025-02-28T16:41:19Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\api\__init__.py:585} ERROR - Collection not found
[2025-02-28T16:41:19Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'bbox'
[2025-02-28T16:41:19Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'crs'
[2025-02-28T16:41:19Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'name'
[2025-02-28T16:41:19Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'bundesland'
[2025-02-28T16:41:19Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'emri_2020'
[2025-02-28T16:41:19Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'emri_2021'
[2025-02-28T16:41:19Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'rel'
[2025-02-28T16:41:19Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'type'
[2025-02-28T16:41:19Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'title'
[2025-02-28T16:41:19Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'href'
[2025-02-28T16:41:19Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'rel'
[2025-02-28T16:41:19Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'type'
[2025-02-28T16:41:19Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'title'
[2025-02-28T16:41:19Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'href'
[2025-02-28T16:41:19Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'rel'
[2025-02-28T16:41:19Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'type'
[2025-02-28T16:41:19Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'title'
[2025-02-28T16:41:19Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'href'
[2025-02-28T16:41:19Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:41:19] "[33mGET /oapi/collections/emri/ HTTP/1.1[0m" 404 -
[2025-02-28T16:41:19Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:41:19] "[33mGET /static/css/default.css HTTP/1.1[0m" 404 -
[2025-02-28T16:41:19Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:41:19] "[33mGET /static/img/logo.png HTTP/1.1[0m" 404 -
[2025-02-28T16:41:19Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:41:19] "[33mGET /static/img/pygeoapi.png HTTP/1.1[0m" 404 -
[2025-02-28T16:41:19Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\api\__init__.py:585} ERROR - Collection not found
[2025-02-28T16:41:19Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:41:19] "[33mGET /oapi/collections/emri/?f=jsonld HTTP/1.1[0m" 404 -
[2025-02-28T16:41:24Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:41:24] "[33mGET /oapi/collections/ HTTP/1.1[0m" 404 -
[2025-02-28T16:41:29Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'bbox'
[2025-02-28T16:41:29Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'crs'
[2025-02-28T16:41:29Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'name'
[2025-02-28T16:41:29Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'bundesland'
[2025-02-28T16:41:29Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'emri_2020'
[2025-02-28T16:41:29Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'emri_2021'
[2025-02-28T16:41:29Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'rel'
[2025-02-28T16:41:29Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'type'
[2025-02-28T16:41:29Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'title'
[2025-02-28T16:41:29Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'href'
[2025-02-28T16:41:29Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'rel'
[2025-02-28T16:41:29Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'type'
[2025-02-28T16:41:29Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'title'
[2025-02-28T16:41:29Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'href'
[2025-02-28T16:41:29Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'rel'
[2025-02-28T16:41:29Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'type'
[2025-02-28T16:41:29Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'title'
[2025-02-28T16:41:29Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\pygeoapi\l10n.py:87} WARNING - unknown locale 'href'
[2025-02-28T16:41:29Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:41:29] "GET /oapi/collections/emri HTTP/1.1" 200 -
[2025-02-28T16:41:30Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:41:30] "[33mGET /static/css/default.css HTTP/1.1[0m" 404 -
[2025-02-28T16:41:30Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:41:30] "[33mGET /static/img/logo.png HTTP/1.1[0m" 404 -
[2025-02-28T16:41:30Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:41:30] "[33mGET /static/img/pygeoapi.png HTTP/1.1[0m" 404 -
[2025-02-28T16:41:30Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:41:30] "GET /oapi/collections/emri?f=jsonld HTTP/1.1" 200 -
[2025-02-28T16:41:32Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:41:32] "[33mGET /collections/emri/items HTTP/1.1[0m" 404 -
[2025-02-28T16:41:34Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:41:34] "[33mGET /collections/emri/items HTTP/1.1[0m" 404 -
[2025-02-28T16:41:37Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:41:37] "[33mGET /collections/emri/queryables HTTP/1.1[0m" 404 -
[2025-02-28T16:41:39Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:41:39] "[33mGET /collections/emri HTTP/1.1[0m" 404 -
[2025-02-28T16:41:41Z] {C:\Uni_Skripts\SII_final\.venv\Lib\site-packages\werkzeug\_internal.py:97} INFO - 127.0.0.1 - - [28/Feb/2025 16:41:41] "[33mGET /collections/emri/items?f=geojson HTTP/1.1[0m" 404 -
